# Generated by Django 3.2.5 on 2021-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20210705_1036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['headline']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='SubCategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='headline',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='title',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='Category',
            field=models.ManyToManyField(to='menu.Category'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='headline',
            field=models.CharField(default='', max_length=100),
        ),
    ]
